#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
//
// The Original Code is MiNET.
//
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
//
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2020 Niclas Olofsson.
// All Rights Reserved.

#endregion

using System.Globalization;
using System.Text;

namespace MiNET.ProtocolGen;

public static class GeneratedFile
{
	public const string LicenseHeader = """
		#region LICENSE

		// The contents of this file are subject to the Common Public Attribution
		// License Version 1.0. (the "License"); you may not use this file except in
		// compliance with the License. You may obtain a copy of the License at
		// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
		// The License is based on the Mozilla Public License Version 1.1, but Sections 14
		// and 15 have been added to cover use of software over a computer network and
		// provide for limited attribution for the Original Developer. In addition, Exhibit A has
		// been modified to be consistent with Exhibit B.
		//
		// Software distributed under the License is distributed on an "AS IS" basis,
		// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
		// the specific language governing rights and limitations under the License.
		//
		// The Original Code is MiNET.
		//
		// The Original Developer is the Initial Developer.  The Initial Developer of
		// the Original Code is Niclas Olofsson.
		//
		// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson.
		// All Rights Reserved.

		#endregion

		""";

	public static void Write(string path, StringBuilder content)
	{
		// Match the repo's generated-file conventions: UTF-8 with BOM, no final newline.
		File.WriteAllText(path, content.ToString().TrimEnd('\r', '\n'), new UTF8Encoding(true));
	}

	public static int IdValue(string id)
	{
		string hex = id.StartsWith("0x") ? id.Substring(2) : id;
		return int.Parse(hex, NumberStyles.HexNumber);
	}
}

/// <summary>
///     Emits MCPE Protocol Registry.cs: the handler interfaces, the client dispatcher and the
///     packet factory, covering the XML pdus and the Cereal roster together. The output is the
///     same code the T4 template emitted when it owned these blocks.
/// </summary>
public static class RegistryEmitter
{
	public static void Emit(string path, List<XmlPdu> xmlPdus, List<RosterEntry> roster)
	{
		// The XML is in id order; fold the roster packets in at their id positions so the
		// output reads as one protocol, not two lists. The interfaces and the dispatcher cover
		// everything except raknet (the T4 selectors only excluded raknet, so ftl is included);
		// the factory's mcpe switch covers the mcpe namespace only, ftl has its own switch.
		var mcpe = new List<(int idValue, string id, string typeName, bool client, bool server)>();
		var handled = new List<(int idValue, string id, string typeName, bool client, bool server)>();
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace != "raknet"))
		{
			var item = (GeneratedFile.IdValue(pdu.Id), pdu.Id, CodeNames.CodeTypeName(pdu.Name), pdu.Client, pdu.Server);
			handled.Add(item);
			if (pdu.Namespace != "ftl") mcpe.Add(item);
		}
		foreach (RosterEntry entry in roster)
		{
			var item = (GeneratedFile.IdValue(entry.Id), entry.Id, entry.TypeName, entry.Client, entry.Server);
			handled.Add(item);
			mcpe.Add(item);
		}
		mcpe.Sort((a, b) => a.idValue.CompareTo(b.idValue));
		handled.Sort((a, b) => a.idValue.CompareTo(b.idValue));

		var sb = new StringBuilder();
		sb.Append(GeneratedFile.LicenseHeader);
		sb.AppendLine();
		sb.AppendLine("//");
		sb.AppendLine("// WARNING: GENERATED CODE - DO NOT EDIT");
		sb.AppendLine("// Generated by MiNET.ProtocolGen from MCPE Protocol.xml and roster.json.");
		sb.AppendLine("//");
		sb.AppendLine();
		sb.AppendLine("using System;");
		sb.AppendLine("using MiNET.Net.RakNet;");
		sb.AppendLine();
		sb.AppendLine("namespace MiNET.Net");
		sb.AppendLine("{");

		sb.AppendLine("\tpublic interface IMcpeMessageHandler");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tvoid Disconnect(string reason, bool sendDisconnect = true);");
		sb.AppendLine();
		foreach (var p in handled.Where(p => p.client))
		{
			sb.AppendLine($"\t\tvoid Handle{p.typeName}({p.typeName} message);");
		}
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic interface IMcpeClientMessageHandler");
		sb.AppendLine("\t{");
		foreach (var p in handled.Where(p => p.server))
		{
			sb.AppendLine($"\t\tvoid Handle{p.typeName}({p.typeName} message);");
		}
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic class McpeClientMessageDispatcher");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tprivate IMcpeClientMessageHandler _messageHandler = null;");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic McpeClientMessageDispatcher(IMcpeClientMessageHandler messageHandler)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_messageHandler = messageHandler;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic bool HandlePacket(Packet message)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tswitch (message)");
		sb.AppendLine("\t\t\t{");
		foreach (var p in handled.Where(p => p.server))
		{
			sb.AppendLine($"\t\t\t\tcase {p.typeName} msg:");
			sb.AppendLine($"\t\t\t\t\t_messageHandler.Handle{p.typeName}(msg);");
			sb.AppendLine("\t\t\t\t\tbreak;");
		}
		sb.AppendLine("\t\t\t\tdefault:");
		sb.AppendLine("\t\t\t\t\treturn false;");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\treturn true;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine();

		sb.AppendLine("\tpublic class PacketFactory");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\tpublic static ICustomPacketFactory CustomPacketFactory { get; set; } = null;");
		sb.AppendLine();
		sb.AppendLine("\t\tpublic static Packet Create(int messageId, ReadOnlyMemory<byte> buffer, string ns)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\tPacket packet = CustomPacketFactory?.Create(messageId, buffer, ns);");
		sb.AppendLine("\t\t\tif (packet != null) return packet;");
		sb.AppendLine();
		sb.AppendLine("\t\t\tif(ns == \"raknet\") ");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace == "raknet"))
		{
			sb.AppendLine($"\t\t\t\t\tcase {pdu.Id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {CodeNames.CodeTypeName(pdu.Name)}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t} else if(ns == \"ftl\") ");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (XmlPdu pdu in xmlPdus.Where(p => p.Namespace == "ftl"))
		{
			sb.AppendLine($"\t\t\t\t\tcase {pdu.Id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {CodeNames.CodeTypeName(pdu.Name)}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t} else {");
		sb.AppendLine();
		sb.AppendLine("\t\t\t\tswitch (messageId)");
		sb.AppendLine("\t\t\t\t{");
		foreach (var p in mcpe)
		{
			sb.AppendLine($"\t\t\t\t\tcase {p.id}:");
			sb.AppendLine($"\t\t\t\t\t\treturn {p.typeName}.CreateObject().Decode(buffer);");
		}
		sb.AppendLine("\t\t\t\t}");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\treturn null;");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");

		GeneratedFile.Write(path, sb);
	}
}

/// <summary>
///     Emits MCPE Protocol Cereal.cs: the packet classes generated from the Mojang schemas, in
///     exactly the shape the T4 template emits for XML packets.
/// </summary>
public static class CerealEmitter
{
	public static void Emit(string path, List<CerealPacket> packets, Dictionary<string, CerealStruct> structs)
	{
		var sb = new StringBuilder();
		sb.Append(GeneratedFile.LicenseHeader);
		sb.AppendLine();
		sb.AppendLine("//");
		sb.AppendLine("// WARNING: GENERATED CODE - DO NOT EDIT");
		sb.AppendLine("// Generated by MiNET.ProtocolGen from the Mojang schemas in MiNET.BlockGen/ProtocolDocs/json");
		sb.AppendLine("// (pinned to the release the protocol targets) plus roster.json and overrides.json.");
		sb.AppendLine("//");
		sb.AppendLine();
		sb.AppendLine("using System;");
		sb.AppendLine("using System.Collections.Generic;");
		sb.AppendLine("using System.Numerics;");
		sb.AppendLine("using MiNET.Utils;");
		sb.AppendLine("using MiNET.Utils.Nbt;");
		sb.AppendLine("using MiNET.Utils.Vectors;");
		sb.AppendLine();
		sb.AppendLine("namespace MiNET.Net");
		sb.AppendLine("{");

		foreach (CerealPacket packet in packets.OrderBy(p => GeneratedFile.IdValue(p.Entry.Id)))
		{
			string typeName = packet.Entry.TypeName;
			string baseType = packet.Entry.Online ? "ConnectedPacket" : "Packet";

			sb.AppendLine($"\tpublic partial class {typeName} : {baseType}<{typeName}>");
			sb.AppendLine("\t{");
			foreach (CerealEnum e in packet.Enums)
			{
				sb.AppendLine($"\t\tpublic enum {e.Name}");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < e.Values.Count; i++)
				{
					sb.AppendLine($"\t\t\t{e.Values[i]} = {i},");
				}
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				sb.AppendLine($"\t\tpublic {field.CsType} {field.FieldName}; // = null;");
			}
			sb.AppendLine();
			sb.AppendLine($"\t\tpublic {typeName}()");
			sb.AppendLine("\t\t{");
			sb.AppendLine($"\t\t\tId = {packet.Entry.Id};");
			sb.AppendLine("\t\t\tIsMcpe = true;");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void EncodePacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.EncodePacket();");
			sb.AppendLine();
			sb.AppendLine("\t\t\tBeforeEncode();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				foreach (string line in EncodeLines(field)) sb.AppendLine($"\t\t\t{line}");
			}
			sb.AppendLine();
			sb.AppendLine("\t\t\tAfterEncode();");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tpartial void BeforeEncode();");
			sb.AppendLine("\t\tpartial void AfterEncode();");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void DecodePacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.DecodePacket();");
			sb.AppendLine();
			sb.AppendLine("\t\t\tBeforeDecode();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				foreach (string line in DecodeLines(field)) sb.AppendLine($"\t\t\t{line}");
			}
			sb.AppendLine();
			sb.AppendLine("\t\t\tAfterDecode();");
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t\tpartial void BeforeDecode();");
			sb.AppendLine("\t\tpartial void AfterDecode();");
			sb.AppendLine();
			sb.AppendLine("\t\tprotected override void ResetPacket()");
			sb.AppendLine("\t\t{");
			sb.AppendLine("\t\t\tbase.ResetPacket();");
			sb.AppendLine();
			foreach (CerealField field in packet.Fields)
			{
				sb.AppendLine($"\t\t\t{field.FieldName}=default({field.CsType});");
			}
			sb.AppendLine("\t\t}");
			sb.AppendLine();
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		foreach (string baseName in structs.Values.Where(s => s.BaseName != null).Select(s => s.BaseName).Distinct().OrderBy(n => n))
		{
			sb.AppendLine($"\tpublic abstract class {baseName}");
			sb.AppendLine("\t{");
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		foreach (CerealStruct s in structs.Values.OrderBy(s => s.Name))
		{
			string inherit = s.BaseName != null ? $" : {s.BaseName}" : "";
			sb.AppendLine($"\tpublic class {s.Name}{inherit}");
			sb.AppendLine("\t{");
			foreach (CerealEnum e in s.Enums)
			{
				sb.AppendLine($"\t\tpublic enum {e.Name}");
				sb.AppendLine("\t\t{");
				for (int i = 0; i < e.Values.Count; i++)
				{
					sb.AppendLine($"\t\t\t{e.Values[i]} = {i},");
				}
				sb.AppendLine("\t\t}");
				sb.AppendLine();
			}
			foreach (CerealField field in s.Fields.Where(f => f.ConstValue == null))
			{
				sb.AppendLine($"\t\tpublic {field.CsType} {field.FieldName};");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		if (structs.Count > 0)
		{
			sb.AppendLine("\tpublic abstract partial class Packet");
			sb.AppendLine("\t{");
			bool first = true;
			foreach (CerealStruct s in structs.Values.OrderBy(s => s.Name))
			{
				if (!first) sb.AppendLine();
				first = false;
				sb.AppendLine($"\t\tpublic void Write({s.Name} data)");
				sb.AppendLine("\t\t{");
				foreach (CerealField field in s.Fields)
				{
					foreach (string line in StructWriteLines(field)) sb.AppendLine($"\t\t\t{line}");
				}
				sb.AppendLine("\t\t}");
				sb.AppendLine();
				sb.AppendLine($"\t\tpublic {s.Name} Read{s.Name}()");
				sb.AppendLine("\t\t{");
				sb.AppendLine($"\t\t\tvar data = new {s.Name}();");
				foreach (CerealField field in s.Fields)
				{
					foreach (string line in StructReadLines(field)) sb.AppendLine($"\t\t\t{line}");
				}
				sb.AppendLine("\t\t\treturn data;");
				sb.AppendLine("\t\t}");
			}
			sb.AppendLine("\t}");
			sb.AppendLine();
		}

		sb.AppendLine("}");

		GeneratedFile.Write(path, sb);
	}

	private static IEnumerable<string> StructWriteLines(CerealField field)
	{
		if (field.ConstValue != null)
		{
			yield return string.Format(field.Type.Write, "");
			yield break;
		}
		foreach (string line in WriteLines(field, "data.")) yield return line;
	}

	private static IEnumerable<string> StructReadLines(CerealField field)
	{
		if (field.ConstValue != null)
		{
			yield return field.Type.Read;
			yield break;
		}
		foreach (string line in ReadLines(field, "data.")) yield return line;
	}

	private static IEnumerable<string> EncodeLines(CerealField field)
	{
		if (field.Kind == FieldKind.Variant)
		{
			yield return $"switch ({field.FieldName})";
			yield return "{";
			for (int i = 0; i < field.Variant.Options.Count; i++)
			{
				yield return $"\tcase {field.Variant.Options[i].Name} v{i}:";
				yield return $"\t\tWriteUnsignedVarInt({i});";
				yield return $"\t\tWrite(v{i});";
				yield return "\t\tbreak;";
			}
			yield return "\tdefault:";
			yield return $"\t\tthrow new Exception($\"{field.FieldName} variant not set or unknown: {{{field.FieldName}}}\");";
			yield return "}";
			yield break;
		}

		foreach (string line in WriteLines(field, "")) yield return line;
	}

	private static IEnumerable<string> DecodeLines(CerealField field)
	{
		if (field.Kind == FieldKind.Variant)
		{
			yield return $"{field.FieldName} = ReadUnsignedVarInt() switch";
			yield return "{";
			for (int i = 0; i < field.Variant.Options.Count; i++)
			{
				yield return $"\t{i} => Read{field.Variant.Options[i].Name}(),";
			}
			yield return $"\tuint other => throw new Exception($\"Unknown {field.FieldName} variant tag {{other}}\"),";
			yield return "};";
			yield break;
		}

		foreach (string line in ReadLines(field, "")) yield return line;
	}

	private static IEnumerable<string> WriteLines(CerealField field, string prefix)
	{
		string name = prefix + field.FieldName;

		if (field.Kind == FieldKind.Struct)
		{
			if (field.Optional)
			{
				yield return $"Write({name} != null);";
				yield return $"if ({name} != null) Write({name});";
			}
			else
			{
				yield return $"Write({name});";
			}
			yield break;
		}

		if (field.Kind == FieldKind.Array)
		{
			yield return $"WriteUnsignedVarInt((uint) {name}.Count);";
			string writeItem = field.Element.Kind == FieldKind.Struct ? "Write(item);" : string.Format(field.Element.Type.Write, "item");
			yield return $"foreach ({field.Element.CsType} item in {name}) {writeItem}";
			yield break;
		}

		if (field.Optional)
		{
			string value = field.IsValueType ? name + ".Value" : name;
			yield return $"Write({name} != null);";
			yield return $"if ({name} != null) {string.Format(field.Type.Write, value)}";
			yield break;
		}

		yield return string.Format(field.Type.Write, name);
	}

	private static IEnumerable<string> ReadLines(CerealField field, string prefix)
	{
		string name = prefix + field.FieldName;

		if (field.Kind == FieldKind.Struct)
		{
			if (field.Optional)
			{
				yield return $"if (ReadBool()) {name} = Read{field.Struct.Name}();";
			}
			else
			{
				yield return $"{name} = Read{field.Struct.Name}();";
			}
			yield break;
		}

		if (field.Kind == FieldKind.Array)
		{
			yield return $"uint {field.FieldName}Count = ReadUnsignedVarInt();";
			yield return $"{name} = new List<{field.Element.CsType}>((int) {field.FieldName}Count);";
			yield return $"for (int i = 0; i < {field.FieldName}Count; i++) {name}.Add({ReadExpression(field.Element)});";
			yield break;
		}

		if (field.Optional)
		{
			yield return $"if (ReadBool()) {name} = {ReadExpression(field)};";
			yield break;
		}

		yield return string.Format(field.Type.Read, name);
	}

	/// <summary>The read call as an expression, for array elements: "ReadString()" from "{0} = ReadString();".</summary>
	private static string ReadExpression(CerealField element)
	{
		if (element.Kind == FieldKind.Struct) return $"Read{element.Struct.Name}()";

		string read = string.Format(element.Type.Read, "");
		if (!read.StartsWith(" = ") || !read.EndsWith(";"))
			throw new NotImplementedException($"array element read is not expression-shaped: {element.Type.Read}");
		return read.Substring(3, read.Length - 4);
	}
}
