#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
//
// The Original Code is MiNET.
//
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
//
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson.
// All Rights Reserved.

#endregion

//
// WARNING: GENERATED CODE - DO NOT EDIT
// Generated by MiNET.ProtocolGen from the Mojang schemas in MiNET.BlockGen/ProtocolDocs/json
// (pinned to the release the protocol targets) plus roster.json and overrides.json.
//

using System;
using System.Collections.Generic;
using System.Numerics;
using MiNET.Utils;
using MiNET.Utils.Metadata;
using MiNET.Utils.Nbt;
using MiNET.Utils.Vectors;

namespace MiNET.Net
{
	public partial class McpeResourcePacksInfo : Packet<McpeResourcePacksInfo>
	{

		public bool mustAccept; // = null;
		public bool hasAddonPacks; // = null;
		public bool hasScripts; // = null;
		public bool forceDisableVibrantVisuals; // = null;
		public PackIdVersion worldTemplateIdAndVersion; // = null;
		public List<PackInfoData> resourcePacks; // = null;

		public McpeResourcePacksInfo()
		{
			Id = 0x06;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(mustAccept);
			Write(hasAddonPacks);
			Write(hasScripts);
			Write(forceDisableVibrantVisuals);
			Write(worldTemplateIdAndVersion);
			WriteUnsignedVarInt((uint) resourcePacks.Count);
			foreach (PackInfoData item in resourcePacks) Write(item);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			mustAccept = ReadBool();
			hasAddonPacks = ReadBool();
			hasScripts = ReadBool();
			forceDisableVibrantVisuals = ReadBool();
			worldTemplateIdAndVersion = ReadPackIdVersion();
			uint resourcePacksCount = ReadUnsignedVarInt();
			resourcePacks = new List<PackInfoData>((int) resourcePacksCount);
			for (int i = 0; i < resourcePacksCount; i++) resourcePacks.Add(ReadPackInfoData());

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			mustAccept=default(bool);
			hasAddonPacks=default(bool);
			hasScripts=default(bool);
			forceDisableVibrantVisuals=default(bool);
			worldTemplateIdAndVersion=default(PackIdVersion);
			resourcePacks=default(List<PackInfoData>);
		}

	}

	public partial class McpeResourcePackClientResponse : Packet<McpeResourcePackClientResponse>
	{

		public ResourcePackClientResponse response; // = null;

		public McpeResourcePackClientResponse()
		{
			Id = 0x08;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			switch (response)
			{
				case ResourcePackClientResponseCancel v0:
					WriteUnsignedVarInt(0);
					Write(v0);
					break;
				case ResourcePackClientResponseDownloading v1:
					WriteUnsignedVarInt(1);
					Write(v1);
					break;
				case ResourcePackClientResponseDownloadingFinished v2:
					WriteUnsignedVarInt(2);
					Write(v2);
					break;
				case ResourcePackClientResponseResourcePackStackFinished v3:
					WriteUnsignedVarInt(3);
					Write(v3);
					break;
				default:
					throw new Exception($"response variant not set or unknown: {response}");
			}

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			response = ReadUnsignedVarInt() switch
			{
				0 => ReadResourcePackClientResponseCancel(),
				1 => ReadResourcePackClientResponseDownloading(),
				2 => ReadResourcePackClientResponseDownloadingFinished(),
				3 => ReadResourcePackClientResponseResourcePackStackFinished(),
				uint other => throw new Exception($"Unknown response variant tag {other}"),
			};

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			response=default(ResourcePackClientResponse);
		}

	}

	public partial class McpeStartGame : Packet<McpeStartGame>
	{
		public enum Gametype
		{
			Undefined = 0,
			Survival = 1,
			Creative = 2,
			Adventure = 3,
			Default = 4,
			Spectator = 5,
			Worlddefault = 6,
		}

		public long entityIdSelf; // = null;
		public long runtimeEntityId; // = null;
		public int gameType; // = null;
		public Vector3 position; // = null;
		public Vector2 rotation; // = null;
		public LevelSettings settings; // = null;
		public string levelId; // = null;
		public string levelName; // = null;
		public string templateContentIdentity; // = null;
		public bool isTrial; // = null;
		public SyncedPlayerMovementSettings movementSettings; // = null;
		public ulong levelCurrentTime; // = null;
		public int enchantmentSeed; // = null;
		public List<ServerBlockProperty> blockProperties; // = null;
		public string multiplayerCorrelationId; // = null;
		public bool enableItemStackNetManager; // = null;
		public string serverVersion; // = null;
		public Nbt playerPropertyData; // = null;
		public ulong serverBlockTypeRegistryChecksum; // = null;
		public UUID worldTemplateId; // = null;
		public bool serverEnabledClientsideGeneration; // = null;
		public bool blockNetworkIdsAreHashes; // = null;
		public bool serverAuthSoundEnabled; // = null;
		public ServerConfig serverConfigurationJoinInfo; // = null;
		public ServerTelemetryData serverTelemetryData; // = null;

		public McpeStartGame()
		{
			Id = 0x0b;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			WriteSignedVarLong(entityIdSelf);
			WriteUnsignedVarLong(runtimeEntityId);
			WriteSignedVarInt(gameType);
			Write(position);
			Write(rotation);
			Write(settings);
			Write(levelId);
			Write(levelName);
			Write(templateContentIdentity);
			Write(isTrial);
			Write(movementSettings);
			Write(levelCurrentTime);
			WriteSignedVarInt(enchantmentSeed);
			WriteUnsignedVarInt((uint) blockProperties.Count);
			foreach (ServerBlockProperty item in blockProperties) Write(item);
			Write(multiplayerCorrelationId);
			Write(enableItemStackNetManager);
			Write(serverVersion);
			Write(playerPropertyData);
			Write(serverBlockTypeRegistryChecksum);
			Write(worldTemplateId);
			Write(serverEnabledClientsideGeneration);
			Write(blockNetworkIdsAreHashes);
			Write(serverAuthSoundEnabled);
			Write(serverConfigurationJoinInfo != null);
			if (serverConfigurationJoinInfo != null) Write(serverConfigurationJoinInfo);
			Write(serverTelemetryData);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			entityIdSelf = ReadSignedVarLong();
			runtimeEntityId = ReadUnsignedVarLong();
			gameType = ReadSignedVarInt();
			position = ReadVector3();
			rotation = ReadVector2();
			settings = ReadLevelSettings();
			levelId = ReadString();
			levelName = ReadString();
			templateContentIdentity = ReadString();
			isTrial = ReadBool();
			movementSettings = ReadSyncedPlayerMovementSettings();
			levelCurrentTime = ReadUlong();
			enchantmentSeed = ReadSignedVarInt();
			uint blockPropertiesCount = ReadUnsignedVarInt();
			blockProperties = new List<ServerBlockProperty>((int) blockPropertiesCount);
			for (int i = 0; i < blockPropertiesCount; i++) blockProperties.Add(ReadServerBlockProperty());
			multiplayerCorrelationId = ReadString();
			enableItemStackNetManager = ReadBool();
			serverVersion = ReadString();
			playerPropertyData = ReadNbt();
			serverBlockTypeRegistryChecksum = ReadUlong();
			worldTemplateId = ReadUUID();
			serverEnabledClientsideGeneration = ReadBool();
			blockNetworkIdsAreHashes = ReadBool();
			serverAuthSoundEnabled = ReadBool();
			if (ReadBool()) serverConfigurationJoinInfo = ReadServerConfig();
			serverTelemetryData = ReadServerTelemetryData();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			entityIdSelf=default(long);
			runtimeEntityId=default(long);
			gameType=default(int);
			position=default(Vector3);
			rotation=default(Vector2);
			settings=default(LevelSettings);
			levelId=default(string);
			levelName=default(string);
			templateContentIdentity=default(string);
			isTrial=default(bool);
			movementSettings=default(SyncedPlayerMovementSettings);
			levelCurrentTime=default(ulong);
			enchantmentSeed=default(int);
			blockProperties=default(List<ServerBlockProperty>);
			multiplayerCorrelationId=default(string);
			enableItemStackNetManager=default(bool);
			serverVersion=default(string);
			playerPropertyData=default(Nbt);
			serverBlockTypeRegistryChecksum=default(ulong);
			worldTemplateId=default(UUID);
			serverEnabledClientsideGeneration=default(bool);
			blockNetworkIdsAreHashes=default(bool);
			serverAuthSoundEnabled=default(bool);
			serverConfigurationJoinInfo=default(ServerConfig);
			serverTelemetryData=default(ServerTelemetryData);
		}

	}

	public partial class McpeAddEntity : Packet<McpeAddEntity>
	{

		public long entityIdSelf; // = null;
		public long runtimeEntityId; // = null;
		public string entityType; // = null;
		public Vector3 position; // = null;
		public Vector3 velocity; // = null;
		public Vector2 rotation; // = null;
		public float yHeadRotation; // = null;
		public float yBodyRotation; // = null;
		public EntityAttributes attributes; // = null;
		public MetadataDictionary metadata; // = null;
		public PropertySyncData synchedProperties; // = null;
		public List<ActorLink> links; // = null;

		public McpeAddEntity()
		{
			Id = 0x0d;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			WriteSignedVarLong(entityIdSelf);
			WriteUnsignedVarLong(runtimeEntityId);
			Write(entityType);
			Write(position);
			Write(velocity);
			Write(rotation);
			Write(yHeadRotation);
			Write(yBodyRotation);
			Write(attributes);
			Write(metadata);
			Write(synchedProperties);
			WriteUnsignedVarInt((uint) links.Count);
			foreach (ActorLink item in links) Write(item);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			entityIdSelf = ReadSignedVarLong();
			runtimeEntityId = ReadUnsignedVarLong();
			entityType = ReadString();
			position = ReadVector3();
			velocity = ReadVector3();
			rotation = ReadVector2();
			yHeadRotation = ReadFloat();
			yBodyRotation = ReadFloat();
			attributes = ReadEntityAttributes();
			metadata = ReadMetadataDictionary();
			synchedProperties = ReadPropertySyncData();
			uint linksCount = ReadUnsignedVarInt();
			links = new List<ActorLink>((int) linksCount);
			for (int i = 0; i < linksCount; i++) links.Add(ReadActorLink());

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			entityIdSelf=default(long);
			runtimeEntityId=default(long);
			entityType=default(string);
			position=default(Vector3);
			velocity=default(Vector3);
			rotation=default(Vector2);
			yHeadRotation=default(float);
			yBodyRotation=default(float);
			attributes=default(EntityAttributes);
			metadata=default(MetadataDictionary);
			synchedProperties=default(PropertySyncData);
			links=default(List<ActorLink>);
		}

	}

	public partial class McpeMovePlayer : Packet<McpeMovePlayer>
	{
		public enum Mode
		{
			Normal = 0,
			Respawn = 1,
			Teleport = 2,
			Onlyheadrot = 3,
		}

		public long runtimeEntityId; // = null;
		public Vector3 position; // = null;
		public Vector2 rotation; // = null;
		public float headYaw; // = null;
		public byte mode; // = null;
		public bool onGround; // = null;
		public long ridingRuntimeEntityId; // = null;
		public MovePlayerTeleportData teleportData; // = null;
		public long tick; // = null;

		public McpeMovePlayer()
		{
			Id = 0x13;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			WriteUnsignedVarLong(runtimeEntityId);
			Write(position);
			Write(rotation);
			Write(headYaw);
			Write(mode);
			Write(onGround);
			WriteUnsignedVarLong(ridingRuntimeEntityId);
			Write(teleportData != null);
			if (teleportData != null) Write(teleportData);
			WriteUnsignedVarLong(tick);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			runtimeEntityId = ReadUnsignedVarLong();
			position = ReadVector3();
			rotation = ReadVector2();
			headYaw = ReadFloat();
			mode = ReadByte();
			onGround = ReadBool();
			ridingRuntimeEntityId = ReadUnsignedVarLong();
			if (ReadBool()) teleportData = ReadMovePlayerTeleportData();
			tick = ReadUnsignedVarLong();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			runtimeEntityId=default(long);
			position=default(Vector3);
			rotation=default(Vector2);
			headYaw=default(float);
			mode=default(byte);
			onGround=default(bool);
			ridingRuntimeEntityId=default(long);
			teleportData=default(MovePlayerTeleportData);
			tick=default(long);
		}

	}

	public partial class McpeSetEntityData : Packet<McpeSetEntityData>
	{

		public long runtimeEntityId; // = null;
		public MetadataDictionary metadata; // = null;
		public PropertySyncData synchedProperties; // = null;
		public long tick; // = null;

		public McpeSetEntityData()
		{
			Id = 0x27;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			WriteUnsignedVarLong(runtimeEntityId);
			Write(metadata);
			Write(synchedProperties);
			WriteUnsignedVarLong(tick);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			runtimeEntityId = ReadUnsignedVarLong();
			metadata = ReadMetadataDictionary();
			synchedProperties = ReadPropertySyncData();
			tick = ReadUnsignedVarLong();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			runtimeEntityId=default(long);
			metadata=default(MetadataDictionary);
			synchedProperties=default(PropertySyncData);
			tick=default(long);
		}

	}

	public partial class McpeLevelChunk : Packet<McpeLevelChunk>
	{

		public ChunkPos chunkPosition; // = null;
		public int dimension; // = null;
		public uint subChunkCount; // = null;
		public int? clientRequestSubchunkLimit; // = null;
		public bool cacheEnabled; // = null;
		public List<ulong> cacheMetadata; // = null;
		public byte[] chunkData; // = null;

		public McpeLevelChunk()
		{
			Id = 0x3a;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(chunkPosition);
			WriteSignedVarInt(dimension);
			WriteUnsignedVarInt(subChunkCount);
			Write(clientRequestSubchunkLimit != null);
			if (clientRequestSubchunkLimit != null) WriteSignedVarInt(clientRequestSubchunkLimit.Value);
			Write(cacheEnabled);
			WriteUnsignedVarInt((uint) cacheMetadata.Count);
			foreach (ulong item in cacheMetadata) Write(item);
			WriteByteArray(chunkData);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			chunkPosition = ReadChunkPos();
			dimension = ReadSignedVarInt();
			subChunkCount = ReadUnsignedVarInt();
			if (ReadBool()) clientRequestSubchunkLimit = ReadSignedVarInt();
			cacheEnabled = ReadBool();
			uint cacheMetadataCount = ReadUnsignedVarInt();
			cacheMetadata = new List<ulong>((int) cacheMetadataCount);
			for (int i = 0; i < cacheMetadataCount; i++) cacheMetadata.Add(ReadUlong());
			chunkData = ReadByteArray();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			chunkPosition=default(ChunkPos);
			dimension=default(int);
			subChunkCount=default(uint);
			clientRequestSubchunkLimit=default(int?);
			cacheEnabled=default(bool);
			cacheMetadata=default(List<ulong>);
			chunkData=default(byte[]);
		}

	}

	public partial class McpeAnvilDamage : Packet<McpeAnvilDamage>
	{

		public BlockCoordinates blockPosition; // = null;

		public McpeAnvilDamage()
		{
			Id = 0x8d;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(blockPosition);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			blockPosition = ReadBlockCoordinates();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			blockPosition=default(BlockCoordinates);
		}

	}

	public partial class McpeSubChunkPacket : Packet<McpeSubChunkPacket>
	{

		public bool cacheEnabled; // = null;
		public int dimensionType; // = null;
		public SubChunkPos centerPos; // = null;
		public List<SubChunkPacketData> subchunkData; // = null;

		public McpeSubChunkPacket()
		{
			Id = 0xae;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(cacheEnabled);
			WriteSignedVarInt(dimensionType);
			Write(centerPos);
			WriteUnsignedVarInt((uint) subchunkData.Count);
			foreach (SubChunkPacketData item in subchunkData) Write(item);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			cacheEnabled = ReadBool();
			dimensionType = ReadSignedVarInt();
			centerPos = ReadSubChunkPos();
			uint subchunkDataCount = ReadUnsignedVarInt();
			subchunkData = new List<SubChunkPacketData>((int) subchunkDataCount);
			for (int i = 0; i < subchunkDataCount; i++) subchunkData.Add(ReadSubChunkPacketData());

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			cacheEnabled=default(bool);
			dimensionType=default(int);
			centerPos=default(SubChunkPos);
			subchunkData=default(List<SubChunkPacketData>);
		}

	}

	public abstract class ResourcePackClientResponse
	{
	}

	public class ActorLink
	{
		public enum ActorLinkType
		{
			None = 0,
			Riding = 1,
			Passenger = 2,
		}

		public long targetA;
		public long targetB;
		public byte type;
		public bool immediate;
		public bool passengerInitiated;
		public float vehicleAngularVelocity;
	}

	public class ChunkPos
	{
		public int x;
		public int z;
	}

	public class ClientStoreEntryPointConfig
	{
		public string storeid;
		public string storename;
	}

	public class EduSharedUriResource
	{
		public string buttonName;
		public string linkUri;
	}

	public class GatheringsConfig
	{
		public UUID experienceid;
		public string experiencename;
		public UUID worldid;
		public string worldname;
		public string creatorid;
		public UUID targetid;
		public string scenarioid;
		public string serverid;
	}

	public class LevelSettings
	{
		public enum Generatortype
		{
			Legacy = 0,
			Overworld = 1,
			Flat = 2,
			Nether = 3,
			Theend = 4,
			Void = 5,
			Undefined = 6,
		}

		public enum Gametype
		{
			Undefined = 0,
			Survival = 1,
			Creative = 2,
			Adventure = 3,
			Default = 4,
			Spectator = 5,
			Worlddefault = 6,
		}

		public enum Gamedifficulty
		{
			Peaceful = 0,
			Easy = 1,
			Normal = 2,
			Hard = 3,
			Count = 4,
			Unknown = 5,
		}

		public enum Editorworldtype
		{
			Noneditor = 0,
			Editorproject = 1,
			Editortestlevel = 2,
			Editorrealmsupload = 3,
		}

		public enum Educationeditionoffer
		{
			None = 0,
			Restofworld = 1,
			ChinaDeprecated = 2,
		}

		public enum Xboxlivebroadcastsetting
		{
			Nomultiplay = 0,
			Inviteonly = 1,
			Friendsonly = 2,
			Friendsoffriends = 3,
			Public = 4,
		}

		public enum Platformbroadcastsetting
		{
			Nomultiplay = 0,
			Inviteonly = 1,
			Friendsonly = 2,
			Friendsoffriends = 3,
			Public = 4,
		}

		public enum Playerpermissions
		{
			Visitor = 0,
			Member = 1,
			Operator = 2,
			Custom = 3,
		}

		public enum Chatrestrictionlevel
		{
			None = 0,
			Dropped = 1,
			Disabled = 2,
		}

		public enum Servereditorconnectionpolicy
		{
			Matchworldtype = 0,
			Editoronly = 1,
			Vanillaonly = 2,
			Mixed = 3,
		}

		public ulong seed;
		public SpawnSettings spawnSettings;
		public int generatorType;
		public int gameType;
		public bool isHardcore;
		public int gameDifficulty;
		public BlockCoordinates defaultSpawnBlockPosition;
		public bool achievementsDisabled;
		public int editorWorldType;
		public bool isCreatedInEditor;
		public bool isExportedFromEditor;
		public int dayCycleStopTime;
		public uint educationEditionOffer;
		public bool educationFeaturesEnabled;
		public string educationProductId;
		public float rainLevel;
		public float lightningLevel;
		public bool hasConfirmedPlatformLockedContent;
		public bool multiplayerGameIntent;
		public bool lanBroadcastIntent;
		public int xboxLiveBroadcastSetting;
		public int platformBroadcastSetting;
		public bool commandsEnabled;
		public bool texturePacksRequired;
		public GameRules gamerules;
		public Experiments experiments;
		public bool hasBonusChestEnabled;
		public bool startWithMapEnabled;
		public sbyte playerPermissions;
		public int serverChunkTickRange;
		public bool hasLockedBehaviorPack;
		public bool hasLockedResourcePack;
		public bool isFromLockedTemplate;
		public bool useMsaGamertagsOnly;
		public bool isFromWorldTemplate;
		public bool isWorldTemplateOptionLocked;
		public bool onlySpawnV1Villagers;
		public bool personaDisabled;
		public bool customSkinsDisabled;
		public bool emoteChatMuted;
		public string baseGameVersion;
		public int limitedWorldWidth;
		public int limitedWorldDepth;
		public bool netherType;
		public EduSharedUriResource eduSharedUriResource;
		public bool? overrideForceExperimentalGameplay;
		public byte chatRestrictionLevel;
		public bool disablePlayerInteractions;
		public int serverEditorConnectionPolicy;
		public bool allowAnonymousBlockDropsInEditorWorlds;
	}

	public class MovePlayerTeleportData
	{
		public int teleportationCause;
		public int sourceActorType;
	}

	public class PackIdVersion
	{
		public UUID packUuid;
		public string packVersion;
	}

	public class PackInfoData
	{
		public PackIdVersion packIdVersion;
		public ulong packSize;
		public string contentKey;
		public string subpackName;
		public string contentIdentity;
		public bool hasScripts;
		public bool isAddonPack;
		public bool isRayTracingCapable;
		public string cdnUrl;
	}

	public class PropertySyncData
	{
		public List<PropertySyncDataPropertySyncIntEntry> intEntriesList;
		public List<PropertySyncDataPropertySyncFloatEntry> floatEntriesList;
	}

	public class PropertySyncDataPropertySyncFloatEntry
	{
		public uint propertyIndex;
		public float data;
	}

	public class PropertySyncDataPropertySyncIntEntry
	{
		public uint propertyIndex;
		public int data;
	}

	public class ResourcePackClientResponseCancel : ResourcePackClientResponse
	{
	}

	public class ResourcePackClientResponseDownloading : ResourcePackClientResponse
	{
		public List<string> downloadingPacks;
	}

	public class ResourcePackClientResponseDownloadingFinished : ResourcePackClientResponse
	{
	}

	public class ResourcePackClientResponseResourcePackStackFinished : ResourcePackClientResponse
	{
	}

	public class ServerBlockProperty
	{
		public string blockName;
		public Nbt blockDefinition;
	}

	public class ServerConfig
	{
		public GatheringsConfig gathering;
		public ClientStoreEntryPointConfig clientstoreentrypoint;
		public string presence;
	}

	public class ServerTelemetryData
	{
		public string serverId;
		public string scenarioId;
		public string worldId;
		public string ownerId;
	}

	public class SpawnSettings
	{
		public enum Spawnbiometype
		{
			Default = 0,
			Userdefined = 1,
		}

		public short spawnBiomeType;
		public string userDefinedBiomeName;
		public int dimension;
	}

	public class SubChunkHeightmapData
	{
		public enum Heightmaptype
		{
			Nodata = 0,
			Hasdata = 1,
			Alltoohigh = 2,
			Alltoolow = 3,
		}

		public enum Renderheightmaptype
		{
			Nodata = 0,
			Hasdata = 1,
			Alltoohigh = 2,
			Alltoolow = 3,
			Allcopied = 4,
		}

		public byte heightMapType;
		public byte[] heights;
		public byte renderHeightMapType;
		public byte[] renderHeights;
	}

	public class SubChunkPacketData
	{
		public enum Subchunkrequestresult
		{
			Success = 0,
			Levelchunkdoesntexist = 1,
			Wrongdimension = 2,
			Playerdoesntexist = 3,
			Indexoutofbounds = 4,
			Successallair = 5,
		}

		public SubChunkPosOffset subchunkPosOffset;
		public byte subchunkRequestResult;
		public byte[] serializedSubChunk;
		public SubChunkHeightmapData heightMapData;
		public ulong? blobId;
	}

	public class SubChunkPos
	{
		public int subchunkPositionX;
		public int subchunkPositionY;
		public int subchunkPositionZ;
	}

	public class SubChunkPosOffset
	{
		public sbyte subchunkOffsetX;
		public sbyte subchunkOffsetY;
		public sbyte subchunkOffsetZ;
	}

	public class SyncedPlayerMovementSettings
	{
		public int rewindHistorySize;
		public bool serverAuthoritativeBlockBreaking;
	}

	public abstract partial class Packet
	{
		public void Write(ActorLink data)
		{
			WriteSignedVarLong(data.targetA);
			WriteSignedVarLong(data.targetB);
			Write(data.type);
			Write(data.immediate);
			Write(data.passengerInitiated);
			Write(data.vehicleAngularVelocity);
		}

		public ActorLink ReadActorLink()
		{
			var data = new ActorLink();
			data.targetA = ReadSignedVarLong();
			data.targetB = ReadSignedVarLong();
			data.type = ReadByte();
			data.immediate = ReadBool();
			data.passengerInitiated = ReadBool();
			data.vehicleAngularVelocity = ReadFloat();
			return data;
		}

		public void Write(ChunkPos data)
		{
			WriteSignedVarInt(data.x);
			WriteSignedVarInt(data.z);
		}

		public ChunkPos ReadChunkPos()
		{
			var data = new ChunkPos();
			data.x = ReadSignedVarInt();
			data.z = ReadSignedVarInt();
			return data;
		}

		public void Write(ClientStoreEntryPointConfig data)
		{
			Write(data.storeid);
			Write(data.storename);
		}

		public ClientStoreEntryPointConfig ReadClientStoreEntryPointConfig()
		{
			var data = new ClientStoreEntryPointConfig();
			data.storeid = ReadString();
			data.storename = ReadString();
			return data;
		}

		public void Write(EduSharedUriResource data)
		{
			Write(data.buttonName);
			Write(data.linkUri);
		}

		public EduSharedUriResource ReadEduSharedUriResource()
		{
			var data = new EduSharedUriResource();
			data.buttonName = ReadString();
			data.linkUri = ReadString();
			return data;
		}

		public void Write(GatheringsConfig data)
		{
			Write(data.experienceid);
			Write(data.experiencename);
			Write(data.worldid);
			Write(data.worldname);
			Write(data.creatorid);
			Write(data.targetid);
			Write(data.scenarioid);
			Write(data.serverid);
		}

		public GatheringsConfig ReadGatheringsConfig()
		{
			var data = new GatheringsConfig();
			data.experienceid = ReadUUID();
			data.experiencename = ReadString();
			data.worldid = ReadUUID();
			data.worldname = ReadString();
			data.creatorid = ReadString();
			data.targetid = ReadUUID();
			data.scenarioid = ReadString();
			data.serverid = ReadString();
			return data;
		}

		public void Write(LevelSettings data)
		{
			Write(data.seed);
			Write(data.spawnSettings);
			WriteSignedVarInt(data.generatorType);
			WriteSignedVarInt(data.gameType);
			Write(data.isHardcore);
			WriteSignedVarInt(data.gameDifficulty);
			Write(data.defaultSpawnBlockPosition);
			Write(data.achievementsDisabled);
			WriteSignedVarInt(data.editorWorldType);
			Write(data.isCreatedInEditor);
			Write(data.isExportedFromEditor);
			WriteSignedVarInt(data.dayCycleStopTime);
			WriteUnsignedVarInt(data.educationEditionOffer);
			Write(data.educationFeaturesEnabled);
			Write(data.educationProductId);
			Write(data.rainLevel);
			Write(data.lightningLevel);
			Write(data.hasConfirmedPlatformLockedContent);
			Write(data.multiplayerGameIntent);
			Write(data.lanBroadcastIntent);
			WriteSignedVarInt(data.xboxLiveBroadcastSetting);
			WriteSignedVarInt(data.platformBroadcastSetting);
			Write(data.commandsEnabled);
			Write(data.texturePacksRequired);
			Write(data.gamerules);
			Write(data.experiments);
			Write(data.hasBonusChestEnabled);
			Write(data.startWithMapEnabled);
			Write((byte) data.playerPermissions);
			Write(data.serverChunkTickRange);
			Write(data.hasLockedBehaviorPack);
			Write(data.hasLockedResourcePack);
			Write(data.isFromLockedTemplate);
			Write(data.useMsaGamertagsOnly);
			Write(data.isFromWorldTemplate);
			Write(data.isWorldTemplateOptionLocked);
			Write(data.onlySpawnV1Villagers);
			Write(data.personaDisabled);
			Write(data.customSkinsDisabled);
			Write(data.emoteChatMuted);
			Write(data.baseGameVersion);
			Write(data.limitedWorldWidth);
			Write(data.limitedWorldDepth);
			Write(data.netherType);
			Write(data.eduSharedUriResource);
			Write(data.overrideForceExperimentalGameplay != null);
			if (data.overrideForceExperimentalGameplay != null) Write(data.overrideForceExperimentalGameplay.Value);
			Write(data.chatRestrictionLevel);
			Write(data.disablePlayerInteractions);
			WriteSignedVarInt(data.serverEditorConnectionPolicy);
			Write(data.allowAnonymousBlockDropsInEditorWorlds);
		}

		public LevelSettings ReadLevelSettings()
		{
			var data = new LevelSettings();
			data.seed = ReadUlong();
			data.spawnSettings = ReadSpawnSettings();
			data.generatorType = ReadSignedVarInt();
			data.gameType = ReadSignedVarInt();
			data.isHardcore = ReadBool();
			data.gameDifficulty = ReadSignedVarInt();
			data.defaultSpawnBlockPosition = ReadBlockCoordinates();
			data.achievementsDisabled = ReadBool();
			data.editorWorldType = ReadSignedVarInt();
			data.isCreatedInEditor = ReadBool();
			data.isExportedFromEditor = ReadBool();
			data.dayCycleStopTime = ReadSignedVarInt();
			data.educationEditionOffer = ReadUnsignedVarInt();
			data.educationFeaturesEnabled = ReadBool();
			data.educationProductId = ReadString();
			data.rainLevel = ReadFloat();
			data.lightningLevel = ReadFloat();
			data.hasConfirmedPlatformLockedContent = ReadBool();
			data.multiplayerGameIntent = ReadBool();
			data.lanBroadcastIntent = ReadBool();
			data.xboxLiveBroadcastSetting = ReadSignedVarInt();
			data.platformBroadcastSetting = ReadSignedVarInt();
			data.commandsEnabled = ReadBool();
			data.texturePacksRequired = ReadBool();
			data.gamerules = ReadGameRules();
			data.experiments = ReadExperiments();
			data.hasBonusChestEnabled = ReadBool();
			data.startWithMapEnabled = ReadBool();
			data.playerPermissions = (sbyte) ReadByte();
			data.serverChunkTickRange = ReadInt();
			data.hasLockedBehaviorPack = ReadBool();
			data.hasLockedResourcePack = ReadBool();
			data.isFromLockedTemplate = ReadBool();
			data.useMsaGamertagsOnly = ReadBool();
			data.isFromWorldTemplate = ReadBool();
			data.isWorldTemplateOptionLocked = ReadBool();
			data.onlySpawnV1Villagers = ReadBool();
			data.personaDisabled = ReadBool();
			data.customSkinsDisabled = ReadBool();
			data.emoteChatMuted = ReadBool();
			data.baseGameVersion = ReadString();
			data.limitedWorldWidth = ReadInt();
			data.limitedWorldDepth = ReadInt();
			data.netherType = ReadBool();
			data.eduSharedUriResource = ReadEduSharedUriResource();
			if (ReadBool()) data.overrideForceExperimentalGameplay = ReadBool();
			data.chatRestrictionLevel = ReadByte();
			data.disablePlayerInteractions = ReadBool();
			data.serverEditorConnectionPolicy = ReadSignedVarInt();
			data.allowAnonymousBlockDropsInEditorWorlds = ReadBool();
			return data;
		}

		public void Write(MovePlayerTeleportData data)
		{
			Write(data.teleportationCause);
			Write(data.sourceActorType);
		}

		public MovePlayerTeleportData ReadMovePlayerTeleportData()
		{
			var data = new MovePlayerTeleportData();
			data.teleportationCause = ReadInt();
			data.sourceActorType = ReadInt();
			return data;
		}

		public void Write(PackIdVersion data)
		{
			Write(data.packUuid);
			Write(data.packVersion);
		}

		public PackIdVersion ReadPackIdVersion()
		{
			var data = new PackIdVersion();
			data.packUuid = ReadUUID();
			data.packVersion = ReadString();
			return data;
		}

		public void Write(PackInfoData data)
		{
			Write(data.packIdVersion);
			Write(data.packSize);
			Write(data.contentKey);
			Write(data.subpackName);
			Write(data.contentIdentity);
			Write(data.hasScripts);
			Write(data.isAddonPack);
			Write(data.isRayTracingCapable);
			Write(data.cdnUrl);
		}

		public PackInfoData ReadPackInfoData()
		{
			var data = new PackInfoData();
			data.packIdVersion = ReadPackIdVersion();
			data.packSize = ReadUlong();
			data.contentKey = ReadString();
			data.subpackName = ReadString();
			data.contentIdentity = ReadString();
			data.hasScripts = ReadBool();
			data.isAddonPack = ReadBool();
			data.isRayTracingCapable = ReadBool();
			data.cdnUrl = ReadString();
			return data;
		}

		public void Write(PropertySyncData data)
		{
			WriteUnsignedVarInt((uint) data.intEntriesList.Count);
			foreach (PropertySyncDataPropertySyncIntEntry item in data.intEntriesList) Write(item);
			WriteUnsignedVarInt((uint) data.floatEntriesList.Count);
			foreach (PropertySyncDataPropertySyncFloatEntry item in data.floatEntriesList) Write(item);
		}

		public PropertySyncData ReadPropertySyncData()
		{
			var data = new PropertySyncData();
			uint intEntriesListCount = ReadUnsignedVarInt();
			data.intEntriesList = new List<PropertySyncDataPropertySyncIntEntry>((int) intEntriesListCount);
			for (int i = 0; i < intEntriesListCount; i++) data.intEntriesList.Add(ReadPropertySyncDataPropertySyncIntEntry());
			uint floatEntriesListCount = ReadUnsignedVarInt();
			data.floatEntriesList = new List<PropertySyncDataPropertySyncFloatEntry>((int) floatEntriesListCount);
			for (int i = 0; i < floatEntriesListCount; i++) data.floatEntriesList.Add(ReadPropertySyncDataPropertySyncFloatEntry());
			return data;
		}

		public void Write(PropertySyncDataPropertySyncFloatEntry data)
		{
			WriteUnsignedVarInt(data.propertyIndex);
			Write(data.data);
		}

		public PropertySyncDataPropertySyncFloatEntry ReadPropertySyncDataPropertySyncFloatEntry()
		{
			var data = new PropertySyncDataPropertySyncFloatEntry();
			data.propertyIndex = ReadUnsignedVarInt();
			data.data = ReadFloat();
			return data;
		}

		public void Write(PropertySyncDataPropertySyncIntEntry data)
		{
			WriteUnsignedVarInt(data.propertyIndex);
			WriteSignedVarInt(data.data);
		}

		public PropertySyncDataPropertySyncIntEntry ReadPropertySyncDataPropertySyncIntEntry()
		{
			var data = new PropertySyncDataPropertySyncIntEntry();
			data.propertyIndex = ReadUnsignedVarInt();
			data.data = ReadSignedVarInt();
			return data;
		}

		public void Write(ResourcePackClientResponseCancel data)
		{
			Write("cancel");
		}

		public ResourcePackClientResponseCancel ReadResourcePackClientResponseCancel()
		{
			var data = new ResourcePackClientResponseCancel();
			ReadString();
			return data;
		}

		public void Write(ResourcePackClientResponseDownloading data)
		{
			Write("downloading");
			WriteUnsignedVarInt((uint) data.downloadingPacks.Count);
			foreach (string item in data.downloadingPacks) Write(item);
		}

		public ResourcePackClientResponseDownloading ReadResourcePackClientResponseDownloading()
		{
			var data = new ResourcePackClientResponseDownloading();
			ReadString();
			uint downloadingPacksCount = ReadUnsignedVarInt();
			data.downloadingPacks = new List<string>((int) downloadingPacksCount);
			for (int i = 0; i < downloadingPacksCount; i++) data.downloadingPacks.Add(ReadString());
			return data;
		}

		public void Write(ResourcePackClientResponseDownloadingFinished data)
		{
			Write("downloadingfinished");
		}

		public ResourcePackClientResponseDownloadingFinished ReadResourcePackClientResponseDownloadingFinished()
		{
			var data = new ResourcePackClientResponseDownloadingFinished();
			ReadString();
			return data;
		}

		public void Write(ResourcePackClientResponseResourcePackStackFinished data)
		{
			Write("resourcepackstackfinished");
		}

		public ResourcePackClientResponseResourcePackStackFinished ReadResourcePackClientResponseResourcePackStackFinished()
		{
			var data = new ResourcePackClientResponseResourcePackStackFinished();
			ReadString();
			return data;
		}

		public void Write(ServerBlockProperty data)
		{
			Write(data.blockName);
			Write(data.blockDefinition);
		}

		public ServerBlockProperty ReadServerBlockProperty()
		{
			var data = new ServerBlockProperty();
			data.blockName = ReadString();
			data.blockDefinition = ReadNbt();
			return data;
		}

		public void Write(ServerConfig data)
		{
			Write(data.gathering != null);
			if (data.gathering != null) Write(data.gathering);
			Write(data.clientstoreentrypoint != null);
			if (data.clientstoreentrypoint != null) Write(data.clientstoreentrypoint);
			Write(data.presence != null);
			if (data.presence != null) Write(data.presence);
		}

		public ServerConfig ReadServerConfig()
		{
			var data = new ServerConfig();
			if (ReadBool()) data.gathering = ReadGatheringsConfig();
			if (ReadBool()) data.clientstoreentrypoint = ReadClientStoreEntryPointConfig();
			if (ReadBool()) data.presence = ReadString();
			return data;
		}

		public void Write(ServerTelemetryData data)
		{
			Write(data.serverId);
			Write(data.scenarioId);
			Write(data.worldId);
			Write(data.ownerId);
		}

		public ServerTelemetryData ReadServerTelemetryData()
		{
			var data = new ServerTelemetryData();
			data.serverId = ReadString();
			data.scenarioId = ReadString();
			data.worldId = ReadString();
			data.ownerId = ReadString();
			return data;
		}

		public void Write(SpawnSettings data)
		{
			Write(data.spawnBiomeType);
			Write(data.userDefinedBiomeName);
			WriteSignedVarInt(data.dimension);
		}

		public SpawnSettings ReadSpawnSettings()
		{
			var data = new SpawnSettings();
			data.spawnBiomeType = ReadShort();
			data.userDefinedBiomeName = ReadString();
			data.dimension = ReadSignedVarInt();
			return data;
		}

		public void Write(SubChunkHeightmapData data)
		{
			Write(data.heightMapType);
			Write(data.heights != null);
			if (data.heights != null) Write(data.heights);
			Write(data.renderHeightMapType);
			Write(data.renderHeights != null);
			if (data.renderHeights != null) Write(data.renderHeights);
		}

		public SubChunkHeightmapData ReadSubChunkHeightmapData()
		{
			var data = new SubChunkHeightmapData();
			data.heightMapType = ReadByte();
			if (ReadBool()) data.heights = ReadBytes(256);
			data.renderHeightMapType = ReadByte();
			if (ReadBool()) data.renderHeights = ReadBytes(256);
			return data;
		}

		public void Write(SubChunkPacketData data)
		{
			Write(data.subchunkPosOffset);
			Write(data.subchunkRequestResult);
			Write(data.serializedSubChunk != null);
			if (data.serializedSubChunk != null) WriteByteArray(data.serializedSubChunk);
			Write(data.heightMapData);
			Write(data.blobId != null);
			if (data.blobId != null) Write(data.blobId.Value);
		}

		public SubChunkPacketData ReadSubChunkPacketData()
		{
			var data = new SubChunkPacketData();
			data.subchunkPosOffset = ReadSubChunkPosOffset();
			data.subchunkRequestResult = ReadByte();
			if (ReadBool()) data.serializedSubChunk = ReadByteArray();
			data.heightMapData = ReadSubChunkHeightmapData();
			if (ReadBool()) data.blobId = ReadUlong();
			return data;
		}

		public void Write(SubChunkPos data)
		{
			Write(data.subchunkPositionX);
			Write(data.subchunkPositionY);
			Write(data.subchunkPositionZ);
		}

		public SubChunkPos ReadSubChunkPos()
		{
			var data = new SubChunkPos();
			data.subchunkPositionX = ReadInt();
			data.subchunkPositionY = ReadInt();
			data.subchunkPositionZ = ReadInt();
			return data;
		}

		public void Write(SubChunkPosOffset data)
		{
			Write((byte) data.subchunkOffsetX);
			Write((byte) data.subchunkOffsetY);
			Write((byte) data.subchunkOffsetZ);
		}

		public SubChunkPosOffset ReadSubChunkPosOffset()
		{
			var data = new SubChunkPosOffset();
			data.subchunkOffsetX = (sbyte) ReadByte();
			data.subchunkOffsetY = (sbyte) ReadByte();
			data.subchunkOffsetZ = (sbyte) ReadByte();
			return data;
		}

		public void Write(SyncedPlayerMovementSettings data)
		{
			WriteSignedVarInt(data.rewindHistorySize);
			Write(data.serverAuthoritativeBlockBreaking);
		}

		public SyncedPlayerMovementSettings ReadSyncedPlayerMovementSettings()
		{
			var data = new SyncedPlayerMovementSettings();
			data.rewindHistorySize = ReadSignedVarInt();
			data.serverAuthoritativeBlockBreaking = ReadBool();
			return data;
		}
	}

}