#region LICENSE

// The contents of this file are subject to the Common Public Attribution
// License Version 1.0. (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at
// https://github.com/NiclasOlofsson/MiNET/blob/master/LICENSE.
// The License is based on the Mozilla Public License Version 1.1, but Sections 14
// and 15 have been added to cover use of software over a computer network and
// provide for limited attribution for the Original Developer. In addition, Exhibit A has
// been modified to be consistent with Exhibit B.
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for
// the specific language governing rights and limitations under the License.
//
// The Original Code is MiNET.
//
// The Original Developer is the Initial Developer.  The Initial Developer of
// the Original Code is Niclas Olofsson.
//
// All portions of the code written by Niclas Olofsson are Copyright (c) 2014-2018 Niclas Olofsson.
// All Rights Reserved.

#endregion

//
// WARNING: GENERATED CODE - DO NOT EDIT
// Generated by MiNET.ProtocolGen from the Mojang schemas in MiNET.BlockGen/ProtocolDocs/json
// (pinned to the release the protocol targets) plus roster.json and overrides.json.
//

using System;
using System.Collections.Generic;
using System.Numerics;
using MiNET.Utils;
using MiNET.Utils.Vectors;

namespace MiNET.Net
{
	public partial class McpeResourcePacksInfo : Packet<McpeResourcePacksInfo>
	{

		public bool mustAccept; // = null;
		public bool hasAddonPacks; // = null;
		public bool hasScripts; // = null;
		public bool forceDisableVibrantVisuals; // = null;
		public PackIdVersion worldTemplateIdAndVersion; // = null;
		public List<PackInfoData> resourcePacks; // = null;

		public McpeResourcePacksInfo()
		{
			Id = 0x06;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(mustAccept);
			Write(hasAddonPacks);
			Write(hasScripts);
			Write(forceDisableVibrantVisuals);
			Write(worldTemplateIdAndVersion);
			WriteUnsignedVarInt((uint) resourcePacks.Count);
			foreach (PackInfoData item in resourcePacks) Write(item);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			mustAccept = ReadBool();
			hasAddonPacks = ReadBool();
			hasScripts = ReadBool();
			forceDisableVibrantVisuals = ReadBool();
			worldTemplateIdAndVersion = ReadPackIdVersion();
			uint resourcePacksCount = ReadUnsignedVarInt();
			resourcePacks = new List<PackInfoData>((int) resourcePacksCount);
			for (int i = 0; i < resourcePacksCount; i++) resourcePacks.Add(ReadPackInfoData());

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			mustAccept=default(bool);
			hasAddonPacks=default(bool);
			hasScripts=default(bool);
			forceDisableVibrantVisuals=default(bool);
			worldTemplateIdAndVersion=default(PackIdVersion);
			resourcePacks=default(List<PackInfoData>);
		}

	}

	public partial class McpeResourcePackClientResponse : Packet<McpeResourcePackClientResponse>
	{

		public ResourcePackClientResponse response; // = null;

		public McpeResourcePackClientResponse()
		{
			Id = 0x08;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			switch (response)
			{
				case ResourcePackClientResponseCancel v0:
					WriteUnsignedVarInt(0);
					Write(v0);
					break;
				case ResourcePackClientResponseDownloading v1:
					WriteUnsignedVarInt(1);
					Write(v1);
					break;
				case ResourcePackClientResponseDownloadingFinished v2:
					WriteUnsignedVarInt(2);
					Write(v2);
					break;
				case ResourcePackClientResponseResourcePackStackFinished v3:
					WriteUnsignedVarInt(3);
					Write(v3);
					break;
				default:
					throw new Exception($"response variant not set or unknown: {response}");
			}

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			response = ReadUnsignedVarInt() switch
			{
				0 => ReadResourcePackClientResponseCancel(),
				1 => ReadResourcePackClientResponseDownloading(),
				2 => ReadResourcePackClientResponseDownloadingFinished(),
				3 => ReadResourcePackClientResponseResourcePackStackFinished(),
				uint other => throw new Exception($"Unknown response variant tag {other}"),
			};

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			response=default(ResourcePackClientResponse);
		}

	}

	public partial class McpeMovePlayer : Packet<McpeMovePlayer>
	{
		public enum Mode
		{
			Normal = 0,
			Respawn = 1,
			Teleport = 2,
			Onlyheadrot = 3,
		}

		public long runtimeEntityId; // = null;
		public Vector3 position; // = null;
		public Vector2 rotation; // = null;
		public float headYaw; // = null;
		public byte mode; // = null;
		public bool onGround; // = null;
		public long ridingRuntimeEntityId; // = null;
		public MovePlayerTeleportData teleportData; // = null;
		public long tick; // = null;

		public McpeMovePlayer()
		{
			Id = 0x13;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			WriteUnsignedVarLong(runtimeEntityId);
			Write(position);
			Write(rotation);
			Write(headYaw);
			Write(mode);
			Write(onGround);
			WriteUnsignedVarLong(ridingRuntimeEntityId);
			Write(teleportData != null);
			if (teleportData != null) Write(teleportData);
			WriteUnsignedVarLong(tick);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			runtimeEntityId = ReadUnsignedVarLong();
			position = ReadVector3();
			rotation = ReadVector2();
			headYaw = ReadFloat();
			mode = ReadByte();
			onGround = ReadBool();
			ridingRuntimeEntityId = ReadUnsignedVarLong();
			if (ReadBool()) teleportData = ReadMovePlayerTeleportData();
			tick = ReadUnsignedVarLong();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			runtimeEntityId=default(long);
			position=default(Vector3);
			rotation=default(Vector2);
			headYaw=default(float);
			mode=default(byte);
			onGround=default(bool);
			ridingRuntimeEntityId=default(long);
			teleportData=default(MovePlayerTeleportData);
			tick=default(long);
		}

	}

	public partial class McpeAnvilDamage : Packet<McpeAnvilDamage>
	{

		public BlockCoordinates blockPosition; // = null;

		public McpeAnvilDamage()
		{
			Id = 0x8d;
			IsMcpe = true;
		}

		protected override void EncodePacket()
		{
			base.EncodePacket();

			BeforeEncode();

			Write(blockPosition);

			AfterEncode();
		}

		partial void BeforeEncode();
		partial void AfterEncode();

		protected override void DecodePacket()
		{
			base.DecodePacket();

			BeforeDecode();

			blockPosition = ReadBlockCoordinates();

			AfterDecode();
		}

		partial void BeforeDecode();
		partial void AfterDecode();

		protected override void ResetPacket()
		{
			base.ResetPacket();

			blockPosition=default(BlockCoordinates);
		}

	}

	public abstract class ResourcePackClientResponse
	{
	}

	public class MovePlayerTeleportData
	{
		public int teleportationCause;
		public int sourceActorType;
	}

	public class PackIdVersion
	{
		public UUID packUuid;
		public string packVersion;
	}

	public class PackInfoData
	{
		public PackIdVersion packIdVersion;
		public ulong packSize;
		public string contentKey;
		public string subpackName;
		public string contentIdentity;
		public bool hasScripts;
		public bool isAddonPack;
		public bool isRayTracingCapable;
		public string cdnUrl;
	}

	public class ResourcePackClientResponseCancel : ResourcePackClientResponse
	{
	}

	public class ResourcePackClientResponseDownloading : ResourcePackClientResponse
	{
		public List<string> downloadingPacks;
	}

	public class ResourcePackClientResponseDownloadingFinished : ResourcePackClientResponse
	{
	}

	public class ResourcePackClientResponseResourcePackStackFinished : ResourcePackClientResponse
	{
	}

	public abstract partial class Packet
	{
		public void Write(MovePlayerTeleportData data)
		{
			Write(data.teleportationCause);
			Write(data.sourceActorType);
		}

		public MovePlayerTeleportData ReadMovePlayerTeleportData()
		{
			var data = new MovePlayerTeleportData();
			data.teleportationCause = ReadInt();
			data.sourceActorType = ReadInt();
			return data;
		}

		public void Write(PackIdVersion data)
		{
			Write(data.packUuid);
			Write(data.packVersion);
		}

		public PackIdVersion ReadPackIdVersion()
		{
			var data = new PackIdVersion();
			data.packUuid = ReadUUID();
			data.packVersion = ReadString();
			return data;
		}

		public void Write(PackInfoData data)
		{
			Write(data.packIdVersion);
			Write(data.packSize);
			Write(data.contentKey);
			Write(data.subpackName);
			Write(data.contentIdentity);
			Write(data.hasScripts);
			Write(data.isAddonPack);
			Write(data.isRayTracingCapable);
			Write(data.cdnUrl);
		}

		public PackInfoData ReadPackInfoData()
		{
			var data = new PackInfoData();
			data.packIdVersion = ReadPackIdVersion();
			data.packSize = ReadUlong();
			data.contentKey = ReadString();
			data.subpackName = ReadString();
			data.contentIdentity = ReadString();
			data.hasScripts = ReadBool();
			data.isAddonPack = ReadBool();
			data.isRayTracingCapable = ReadBool();
			data.cdnUrl = ReadString();
			return data;
		}

		public void Write(ResourcePackClientResponseCancel data)
		{
			Write("cancel");
		}

		public ResourcePackClientResponseCancel ReadResourcePackClientResponseCancel()
		{
			var data = new ResourcePackClientResponseCancel();
			ReadString();
			return data;
		}

		public void Write(ResourcePackClientResponseDownloading data)
		{
			Write("downloading");
			WriteUnsignedVarInt((uint) data.downloadingPacks.Count);
			foreach (string item in data.downloadingPacks) Write(item);
		}

		public ResourcePackClientResponseDownloading ReadResourcePackClientResponseDownloading()
		{
			var data = new ResourcePackClientResponseDownloading();
			ReadString();
			uint downloadingPacksCount = ReadUnsignedVarInt();
			data.downloadingPacks = new List<string>((int) downloadingPacksCount);
			for (int i = 0; i < downloadingPacksCount; i++) data.downloadingPacks.Add(ReadString());
			return data;
		}

		public void Write(ResourcePackClientResponseDownloadingFinished data)
		{
			Write("downloadingfinished");
		}

		public ResourcePackClientResponseDownloadingFinished ReadResourcePackClientResponseDownloadingFinished()
		{
			var data = new ResourcePackClientResponseDownloadingFinished();
			ReadString();
			return data;
		}

		public void Write(ResourcePackClientResponseResourcePackStackFinished data)
		{
			Write("resourcepackstackfinished");
		}

		public ResourcePackClientResponseResourcePackStackFinished ReadResourcePackClientResponseResourcePackStackFinished()
		{
			var data = new ResourcePackClientResponseResourcePackStackFinished();
			ReadString();
			return data;
		}
	}

}